# Website settings
url: "https://donfung.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    projects: "/projects"
#    reading: "/reading"

# Bio settings
name: "Don Fung"
description: "The home page of Don Fung."
thumbnail_path: "profile-photos/donfung_profile.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/don-fung-3099b111a/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/donfung"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:donovanfung@gmail.com"
    label: "Email"
    value: "donovanfung@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown

disqus:
  shortname: donfung

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
